### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Chiroyce1** [Chiroyce1/post-graph#1]
- [x] Add message asking users to reload in case fetching data fails OR auto refresh after 5 seconds ([c480886](https://github.com/Chiroyce1/post-graph/commit/c480886e16e9a4b597413d30ecfb120ac118f4d5))
- [x] Change backend URL to attempt to fix the `Internal Error` error thrown by Replit ([edea8f8](https://github.com/Chiroyce1/post-graph/commit/edea8f8de3f68d21946e836e2af3e057cd981264))
- [ ] Improve the data reset system (quite unstable now)

**Comment by Chiroyce1** [comment]
Data reset system has been removed, and since April Fools' is over, I will attempt to fix it in the coming weeks.
